//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client : RegisteredUser
    {
        public int Id { get; set; }
        public string userID { get; set; }
        public string address { get; set; }
        public string sendOffers { get; set; }
        public string isActive { get; set; }
    }
}
