//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RegisteredUser> RegisteredUsers { get; set; }
        public DbSet<Car> Cars { get; set; }
        public DbSet<PostalTerminal> PostalTerminals { get; set; }
        public DbSet<PostOffice> PostOffices { get; set; }
        public DbSet<DetailedState> DetailedStates { get; set; }
        public DbSet<faultCodes> faultCodes { get; set; }
        public DbSet<Cities> Cities { get; set; }
        public DbSet<Delivery> Deliveries { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<DeliveryState> DeliveryStates { get; set; }
        public DbSet<DeliveryRegistration> DeliveryRegistrations { get; set; }
        public DbSet<Payment> Payments { get; set; }
        public DbSet<payentState> payentStates { get; set; }
        public DbSet<paymentType> paymentTypes { get; set; }
    }
}
