//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RegisteredUser> RegisteredUsers { get; set; }
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<PostalTerminal> PostalTerminals { get; set; }
        public virtual DbSet<PostOffice> PostOffices { get; set; }
        public virtual DbSet<DetailedState> DetailedStates { get; set; }
        public virtual DbSet<faultCodes> faultCodes { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<DeliveryState> DeliveryStates { get; set; }
        public virtual DbSet<DeliveryRegistration> DeliveryRegistrations { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<payentState> payentStates { get; set; }
        public virtual DbSet<paymentType> paymentTypes { get; set; }
    }
}
