//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string paymentStateID { get; set; }
        public string paymentTypeID { get; set; }
        public string date { get; set; }
        public string price { get; set; }
        public int paymentTypeId1 { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual paymentType paymentType { get; set; }
        public virtual payentState payentState { get; set; }
    }
}
