//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryRegistration
    {
        public int Id { get; set; }
        public string registrationDate { get; set; }
        public string validUntil { get; set; }
        public string validFrom { get; set; }
        public int Delivery_Id { get; set; }
    
        public virtual Delivery Delivery { get; set; }
    }
}
