//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedState
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailedState()
        {
            this.PostalTerminals = new HashSet<PostalTerminal>();
        }
    
        public int Id { get; set; }
        public string isWorking { get; set; }
        public string faultCode { get; set; }
        public string isFull { get; set; }
        public string needsService { get; set; }
        public int faultCode1_Id { get; set; }
    
        public virtual faultCode faultCode1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostalTerminal> PostalTerminals { get; set; }
    }
}
