//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.payentStates = new HashSet<payentState>();
        }
    
        public int Id { get; set; }
        public string paymentStateID { get; set; }
        public string paymentTypeID { get; set; }
        public string date { get; set; }
        public string price { get; set; }
        public int paymentTypeId1 { get; set; }
        public int Delivery_Id { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payentState> payentStates { get; set; }
        public virtual paymentType paymentType { get; set; }
    }
}
