//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class postalterminaldbEntities : DbContext
    {
        public postalterminaldbEntities()
            : base("name=postalterminaldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Car> Cars { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Delivery> Deliveries { get; set; }
        public virtual DbSet<DeliveryRegistration> DeliveryRegistrations { get; set; }
        public virtual DbSet<DeliveryState> DeliveryStates { get; set; }
        public virtual DbSet<DetailedState> DetailedStates { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<faultCode> faultCodes { get; set; }
        public virtual DbSet<payentState> payentStates { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<paymentType> paymentTypes { get; set; }
        public virtual DbSet<PostalTerminal> PostalTerminals { get; set; }
        public virtual DbSet<PostOffice> PostOffices { get; set; }
        public virtual DbSet<RegisteredUser> RegisteredUsers { get; set; }
        public virtual DbSet<RegisteredUsers_Admin> RegisteredUsers_Admin { get; set; }
        public virtual DbSet<RegisteredUsers_Client> RegisteredUsers_Client { get; set; }
        public virtual DbSet<RegisteredUsers_Handler> RegisteredUsers_Handler { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
