//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostOffice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostOffice()
        {
            this.RegisteredUsers_Handler = new HashSet<RegisteredUsers_Handler>();
        }
    
        public int Id { get; set; }
        public string cityID { get; set; }
        public string street { get; set; }
        public string employees { get; set; }
        public string shipments { get; set; }
        public string ZIPCode { get; set; }
        public int CitiesId { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegisteredUsers_Handler> RegisteredUsers_Handler { get; set; }
    }
}
