//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUsers_Handler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisteredUsers_Handler()
        {
            this.PostalTerminals = new HashSet<PostalTerminal>();
        }
    
        public int Id { get; set; }
        public string city { get; set; }
        public string car { get; set; }
        public int PostOfficeId { get; set; }
        public int User_id { get; set; }
        public int Car_Id { get; set; }
    
        public virtual Car Car1 { get; set; }
        public virtual PostOffice PostOffice { get; set; }
        public virtual RegisteredUser RegisteredUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostalTerminal> PostalTerminals { get; set; }
    }
}
