//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostalTerminal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredUser
    {
        public int User_id { get; set; }
        public string email { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string registerDate { get; set; }
        public string gender { get; set; }
        public string birthday { get; set; }
    
        public virtual RegisteredUsers_Admin RegisteredUsers_Admin { get; set; }
        public virtual RegisteredUsers_Client RegisteredUsers_Client { get; set; }
        public virtual RegisteredUsers_Handler RegisteredUsers_Handler { get; set; }
    }
}
